"""Add UI fields

Revision ID: 7fe23c6f1c31
Revises: e0439e7f945c
Create Date: 2026-06-01 06:29:24.527244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe23c6f1c31'
down_revision: Union[str, Sequence[str], None] = 'e0439e7f945c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('shipping', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('tax', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.add_column('products', sa.Column('threshold', sa.Integer(), server_default='10', nullable=False))
    op.add_column('products', sa.Column('supplier_name', sa.String(), nullable=True))
    op.add_column('products', sa.Column('supplier_part_number', sa.String(), nullable=True))
    op.add_column('products', sa.Column('visibility_status', sa.String(), server_default='Active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'visibility_status')
    op.drop_column('products', 'supplier_part_number')
    op.drop_column('products', 'supplier_name')
    op.drop_column('products', 'threshold')
    op.drop_column('products', 'description')
    op.drop_column('products', 'category')
    op.drop_column('orders', 'tax')
    op.drop_column('orders', 'shipping')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
